### ISSUE TITLE
Add more questions to assignements

### ISSUE THREAD

**Issue by flor14** [UBC-MDS/ds-toolbox#101]
@joelostblom @armanawn 

I am opening this issue so we track when we finish updating/adding assignments (if we are doing so).
I have to update the ones about merge conflicts, I will do it during this week.

**Comment by armanawn** [comment]
I've just finished adding 4 new questions to assignment 6.

**Comment by joelostblom** [comment]
Done for assignment 2

**Comment by flor14** [comment]
Done for assignment 3, 4 and 5. Can we close this issue?

**Comment by joelostblom** [comment]
yup i believe so
