### ISSUE TITLE
Format across different modules

### ISSUE THREAD

**Issue by flor14** [UBC-MDS/ds-toolbox#11]
I have been looking at the course https://intro-machine-learning.netlify.app/
There are some decisions about formatting that we can imitate so it is the same in all our PRs and we don't have to modify/review them later. Here is a list of the ones I have found, please be free to add others @joelostblom @armanawn 
We can discuss if we agree with them in our next meeting

- [ ] Slide before the exercises
![image](https://user-images.githubusercontent.com/29610858/166299978-b484ac04-fd18-496b-962e-5f489f68bf37.png)

- [ ] **Question #** subtitle when there is more than 1 question in an exercise
![image](https://user-images.githubusercontent.com/29610858/166300025-07180155-70a2-4777-9e31-5687029afe69.png)

- [x] **True or false** subtitle when we have these types of exercises
![image](https://user-images.githubusercontent.com/29610858/166300082-7120da1c-a1be-41f0-a84c-7f8c0645464a.png)

**Comment by flor14** [comment]
* Backticks in hints (formatting problem)
* Separate different lines of code in the options of an MCQ (or include them as images)

**Comment by joelostblom** [comment]
Decision during meeting: No slides, no mcq or T/f titles. Try html tags instead of backticks

**Comment by flor14** [comment]
@joelostblom comment in review

> It would be nice if we could show it as some quote box (like a github quote in grey) instead of the orange outline, but we can add that as a bonus item if we have time. Not sure if `<blockquote>` is enough, depends on the css we have https://www.w3schools.com/html/html_quotation_elements.asp

**Comment by flor14** [comment]
* #52 
* How to add code style formatting to slide's titles?

**Comment by flor14** [comment]
> @joelostblom comment (review chapter 3)
> 
> > It would be nice if we could show it as some quote box (like a github quote in grey) instead of the orange outline, but we can add that as a bonus item if we have time. Not sure if `<blockquote>` is enough, depends on the css we have https://www.w3schools.com/html/html_quotation_elements.asp

The last point refers to this

**Comment by flor14** [comment]
- [ ] When we have multiple choice questions sometimes I used _"A, B and C are correct"_ kind of statements, but in Ines Montani framework the options have no numbers/letters assigned. I have been including them in those cases but action should be taken for all of them.

**Comment by joelostblom** [comment]
I have checked for everything here in my revisions so I am closing this issue
