### ISSUE TITLE
Move the jupyterlab intro slides to module 1

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/ds-toolbox#71]
There are a few slides in [module 7](https://toolbox-learn.mds.ubc.ca/en/module7) that are a basic intro to Jupyterlab, stating what project Jupyter is (slide deck 2, slides 1-5) and giving a tour of the Jupyterlab interface (slide deck 4, slides 1-5). I think it would be valuable to add these slides to module 1 to make sure that all learners get a very basic intro to what jupyterlab is before we start with the shell and git chapters since these use a bit of Jupyterlab. This way we don't have to mention anything about jupyterlab prereqs and they will have everything they need to follow along after the first chapter.

I remember that we discussed this in the beginning and decided to have it in module 7 to start, but that we would consider to move it, and after reading through everything I think it is a better fit in module 1. Module 7 is already long so I don't think this takes away significantly from the content there.

I can make a suggestion for what this looks like when I get to the revision of module 7. What do you think @flor14 and @armanawn ?

**Comment by joelostblom** [comment]
Note to self: I would maybe expand it with screenshots of how to use the terminal either at the end of ch1 or beginning of ch2

**Comment by armanawn** [comment]
@joelostblom I'm onboard with this suggestion; it would be great to see how it's going to look your review of module 7.
